[package]
name = "rust-gitstats"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = "4.5.8"
git2 = { version = "0.19.0", features = ["vendored-libgit2", "vendored-openssl"] }
